### ISSUE TITLE
coi phim sec ko duoc

### ISSUE THREAD

**Issue by nguyenmanhtruongdat** [TuanVo3423/Smile-Eye-Charity#1]
**trang web loi coi phim sec ko duoc** 
![image](https://github.com/TuanVo3423/Smile-Eye-Charity/assets/94544483/c0ac1acd-0838-4dec-9409-9d1243d45cce)

**Comment by TuanVo3423** [comment]
do bạn chưa nạp đầu, donate cho tao, tao cho mày xem
